# Generated by Django 5.1.2 on 2024-10-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
